# Generated by Django 4.2 on 2023-04-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(upload_to='post_imagens')),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
    ]
