# Generated by Django 4.1.4 on 2023-04-15 22:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaApp', '0004_post_slug_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default='', editable=False, null=True, populate_from='titulo', unique=True),
        ),
    ]
